name: Jekyll

on:
  push:
    branches: ["gh-pages"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby on Linux (ubuntu-latest)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev git curl
          git clone https://github.com/rbenv/rbenv.git ~/.rbenv
          git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
          echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $GITHUB_ENV
          echo 'eval "$(rbenv init - bash)"' >> $GITHUB_ENV
          source $GITHUB_ENV
          ~/.rbenv/bin/rbenv install 3.2.2
          ~/.rbenv/bin/rbenv global 3.2.2
          ruby -v
          gem install bundler

      - name: Setup Ruby on macOS
        if: runner.os == 'macOS'
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.2'
          bundler-cache: true

      - name: Setup Ruby on Windows
        if: runner.os == 'Windows'
        run: |
          choco install ruby --version=3.2.2 -y
          refreshenv
          ruby -v
          gem install bundler

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5
        id: pages

      - name: Build Jekyll Site
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production

      - uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
